# ========================
# Perfil ativo padrão: dev
# ========================
spring.profiles.active=dev

# ========================
# Configuração do Swagger
# ========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

server.port=${PORT:8080}
